palavras = [
    'guarda-chuva','endereços', 'lapso', 'crítico', 'pesadelo', 'anunciar', 'cruz', 'revolução', 'eixo', 'vergonha',
    'conde', 'mansão', 'pijamas', 'sofrer', 'esgrima', 'circo', 'errado', 'lógica', 'investimento', 'celular',
    'buquê', 'cerimônia', 'minuto', 'roedor', 'paz', 'gaveta', 'roseta', 'subtrair', 'toque', 'programa',
    'desvantagem', 'sistema solar', 'circular', 'cal', 'segador', 'espantalho', 'barretina', 'ganhos', 'coco',
    'terraplanagem', 'presa', 'esporte', 'coruja', 'diplomata', 'mexidos', 'semeadura', 'sanduíche', 'dedo',
    'gravador', 'bigorna', 'peso', 'carpinteiro', 'trevo', 'topo', 'preencher', 'campo', 'ombros', 'atirar',
    'eletrodomésticos', 'flores', 'doente', 'descoberta', 'sucesso', 'harpa', 'prego', 'pintor', 'fragrância',
    'banimento', 'cotovelo', 'garrafa', 'ganhos', 'diretor', 'aspirar', 'espinafre', 'agudo', 'urgência',
    'carne fria', 'formiga', 'ferradura', 'renda', 'vocal', 'rotas', 'gotas', 'empurre', 'dor', 'alasca',
    'hotel', 'magnetizado', 'articulação', 'abelha', 'ilha', 'sede', 'avisos', 'esgotos', 'uso', 'parede',
    'lama', 'navio', 'fruta', 'teclado', 'luminária', 'viagem', 'sorriso', 'conectar', 'reconhecer', 'brilho',
    'sonho', 'tesouro', 'perdão', 'carinho', 'recomeço', 'montanha', 'fragilidade', 'conquista', 'sabedoria',
    'trabalho', 'inspiração', 'silêncio', 'fronteira', 'saudade', 'pintura', 'manhã', 'felicidade', 'inovação',
    'chocolate', 'paixão', 'aventura', 'caminho', 'nuvem', 'sabão', 'coração', 'tecnologia', 'espelho', 'elefante',
    'vento', 'folha', 'calor', 'abstrato', 'cidade', 'papel', 'ideia', 'floresta', 'lealdade', 'espelho', 'estrela',
    'solução', 'bússola', 'esperança', 'jardim', 'serenidade', 'fotografia', 'paciência', 'bola', 'relógio',
    'abraço', 'ocaso', 'mágica', 'experiência', 'sombra', 'movimento', 'chuva', 'sombra', 'escultura', 'desejo',
    'avaliação', 'soneto', 'arte', 'risada', 'luz', 'imaginário', 'violinista', 'céu', 'navegação', 'colina',
    'girassol', 'vela', 'enigma', 'ópera', 'zumbido', 'voo', 'arcabouço', 'sombra', 'estranho', 'esplendor',
    'máscara', 'sintonia', 'esmeralda', 'mergulho', 'hipnose', 'futuro', 'fragmento', 'diversidade', 'mistério',
    'cantar', 'espelho', 'engrenagem', 'avidez', 'sinfonia', 'oculto', 'vibração', 'apoteose', 'astro', 'mundo',
    'paz', 'estrada', 'oceano', 'sensação', 'sentimento', 'cores', 'estação', 'formação', 'constelação', 'visão',
    'truque', 'melodia', 'cordilheira', 'reflexão', 'conexão', 'proeza', 'firmeza', 'observação', 'composição',
    'alvorada', 'efervescência', 'fragrância', 'despertar', 'equilíbrio', 'laboratório', 'conquistador', 'melancolia',
    'inquietude', 'enigma', 'percepção', 'estratégia', 'domínio', 'sorte', 'escritório', 'vanguarda', 'refúgio',
    'serenata', 'fervor', 'passagem', 'confiança', 'atmosfera', 'cúmplice', 'cavaleiro', 'exaltação', 'suavidade',
    'ternura', 'júbilo', 'época', 'modéstia', 'prestígio', 'cometa', 'devaneio', 'claridade', 'serendipidade',
    'retalho', 'observatório', 'silhueta', 'manancial', 'instante', 'sinergia', 'volúpia', 'avidez', 'comunhão',
    'plenitude', 'silêncio', 'superação', 'essência', 'esmero', 'desdobramento', 'preciosidade', 'convicção',
    'amplitude', 'resiliência', 'arco-íris', 'elaboração', 'entardecer', 'cachoeira', 'profundidade', 'relíquia',
    'vestígio', 'vertigem', 'ilusão', 'complexidade', 'miragem', 'contorno', 'luminosidade', 'riqueza', 'exuberância',
    'deslumbramento', 'discernimento', 'revelação', 'encanto', 'instantâneo', 'reminiscência', 'horizonte', 'tesouro',
    'fascínio', 'orvalho', 'acolhimento', 'trégua', 'cumplicidade',
    'talento', 'ideologia', 'proeza', 'despacho', 'equinócio', 'bisonte', 'inequívoco', 'espreitar', 'paradoxo', 'valentia',
    'elocução', 'benevolência', 'flecha', 'sintonizar', 'melancolia', 'cavalaria', 'quimera', 'renúncia', 'glamouroso',
    'sintetizar', 'silhueta', 'conquistador', 'ventilador', 'folclore', 'excêntrico', 'enigma', 'xenofobia', 'falácia',
    'saudade', 'formidável', 'utopia', 'idílico', 'serenidade', 'holograma', 'estupefato', 'cosmonauta', 'prolixo', 'ninar',
    'procrastinar', 'ânfora', 'tênue', 'estonteante', 'empatia', 'inebriante', 'quixotesco', 'solilóquio', 'effervescente',
    'sonâmbulo', 'efêmero', 'vicissitudes', 'somnolência', 'enlevo', 'voraz', 'plenitude', 'aurora', 'efluvios', 'quadrivium',
    'suntuoso', 'proclamação', 'querência', 'esmero', 'peregrinação', 'cafuné', 'etéreo', 'acústico', 'epifania', 'luminiscência',
    'cintilar', 'paleta', 'bravura', 'intrépido', 'éter', 'quásar', 'embuste', 'disparate', 'vicissitudes', 'vórtice', 'perquirir',
    'sagaz', 'magnânimo', 'pândego', 'grandiloquente', 'sibilante', 'visceral', 'ínfimo', 'lúdico', 'arquétipo', 'paradigma',
    'insólito', 'desventura', 'melodioso', 'luminar', 'crepúsculo', 'cacofonia', 'hipotético', 'sagacidade', 'idiossincrasia',
    'frenesi', 'convalescença', 'peripécia', 'incólume', 'saudosismo', 'intempérie', 'fervilhar', 'seráfico', 'ínclito', 'vislumbrar',
    'prosódia', 'reverberar', 'afável', 'taciturno', 'obnubilar', 'sibilante', 'apoteose', 'escárnio', 'exasperar', 'infindo', 'hodierno']
